/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioRepita;

import javax.swing.JOptionPane;

public class App {
  

    public static void main(String[] args) {
        int numero, soma = 0;
   do   {
       numero = Integer.parseInt (JOptionPane.showInputDialog (null, "<html>Falae um numero: <br><em>"
           + "(se der 0 para) </em></html>"));
       soma += numero;
           }
   while (numero != 0);
   JOptionPane.showMessageDialog(null, "<html>Resultado Final <hr>" + "<br>A soma deles vale " +     soma);
                                      
   }
}



   